"""Auth port — token management interface.

Broker adapters implement this to handle authentication lifecycle:
initial login, token retrieval, and automatic refresh.
"""

from __future__ import annotations

from datetime import datetime
from typing import Callable, Protocol


class AuthPort(Protocol):
    def get_token(self) -> str: ...
    def refresh_token(self) -> str: ...
    def is_authenticated(self) -> bool: ...
    def acquire(self) -> str | None: ...
    def force_refresh(self) -> str | None: ...
    def expires_at(self) -> datetime | None: ...
    def on_token_change(self, callback: Callable[[str], None]) -> None: ...
