"""Domain layer — enterprise business rules with zero external dependencies.

Re-exports all domain types for convenient access::

    from brokers.domain import Order, Side, OrderStatus, BrokerError
"""

from brokers.domain.entities import (
    Balance,
    Candle,
    DepthLevel,
    Holding,
    InstrumentInfo,
    IpoInfo,
    MarketDepth,
    MutualFundHolding,
    NewsItem,
    OptionChain,
    OptionLeg,
    OptionStrike,
    Order,
    OrderRequest,
    OrderResponse,
    Position,
    Quote,
    RiskCheckRequest,
    RiskCheckResult,
    Trade,
    UserProfile,
)
from brokers.domain.enums import (
    AuthMode,
    BrokerID,
    OrderStatus,
    OrderType,
    ProductType,
    Side,
    Validity,
)
from brokers.domain.exceptions import (
    AuthenticationError,
    BrokerDegradedError,
    BrokerError,
    BrokerServerError,
    CircuitOpenError,
    ConfigError,
    DataError,
    InstrumentNotFoundError,
    NetworkError,
    NonRetryableError,
    NotSupportedError,
    OrderRejectedError,
    RateLimitError,
    RetryableError,
    TokenRateLimitError,
    TradeXV2Error,
    ValidationError,
)
from brokers.domain.order_lifecycle import OrderStateError

__all__ = [
    "AuthenticationError",
    "AuthMode",
    "BrokerID",
    "Balance",
    "BrokerDegradedError",
    "BrokerError",
    "BrokerServerError",
    "Candle",
    "CircuitOpenError",
    "ConfigError",
    "DataError",
    "DepthLevel",
    "Holding",
    "InstrumentInfo",
    "InstrumentNotFoundError",
    "IpoInfo",
    "MutualFundHolding",
    "NewsItem",
    "MarketDepth",
    "NetworkError",
    "NonRetryableError",
    "NotSupportedError",
    "OptionChain",
    "OptionLeg",
    "OptionStrike",
    "Order",
    "OrderRejectedError",
    "OrderRequest",
    "OrderResponse",
    "OrderStateError",
    "OrderStatus",
    "OrderType",
    "Position",
    "ProductType",
    "Quote",
    "RateLimitError",
    "RetryableError",
    "RiskCheckRequest",
    "RiskCheckResult",
    "Side",
    "Trade",
    "TokenRateLimitError",
    "TradeXV2Error",
    "UserProfile",
    "ValidationError",
    "Validity",
]
